### ISSUE TITLE
basic client-side complaint map

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/nyc-walkmaper#2]
Here's the description:
>This map will take **either a Complaint ID or a latlng** of a complaint (TBD), highlight that point and the query the 311 data on NYC Socrata for specified complaint types within the last 24 months and within a certain buffer of the Walkmapper complaint location. The buffer will initially be set at 50 feet, but can be adjusted if needed. It would also query the Walkmapper complaints nearby for the database then those would have pop up with details from the database . The 311 markers would have popups with details from 311.

The map would be integrated by the main Walkmapper developer into pages like this:
![image](https://user-images.githubusercontent.com/1423200/134072327-820e4f43-1796-45b7-b4a8-3c884caadfcd.png)

http://walkmapper-admin.chekpeds.com/site/details?id=622

You can log into that with Christine's email `cberthet@me.com` to see the content.

My hope is that this can all be client-side code, and we can run our copy on GH pages out of this repo, and then the Walkmapper dev can either integrate some selfcontained Javascript and HTML/CSS from us into their template or even just iframe in and pass in a `latlng` as part of the iFrame source link, and we take that as a param. 

The 311 query is sorted over in #1 and I think will be straightforward, though coming up with final popup content will take some curation.

The idea of querying the nearby walkmapper complaints was a late addition fro the client. Since we are ETL0ing all those into CARTO, I imagine we can add another API call to our own CARTO data and pull in similar stuff -- within last 24 months and within 50 meters. We could even set the months and meters as more URL params, which would be slick and allow for future flexibility if they want those to change. using the IDs we store in CARTO, we'd need to craft links like `http://walkmapper-admin.chekpeds.com/site/details?id={id}` to make it easy for folks to navigate between Walkmapper map points.

**Comment by gregallensworth** [comment]
I have some basics in place. There was no discussion of design & behavior, so this slapdash pixels-on-screen so we can focus on details.

![image](https://user-images.githubusercontent.com/3117633/135002121-e78d5993-ddd4-4640-aa3a-ee523b376b3b.png)


To do:

**general style stuff**

- [x] zoom home icon is a little off

- [x] the dots in Carto's auto-generated legend (bottom right) are really tiny, can't even distinguish the colors

- [x] almost forgot: GIN credits control

**map zoom**

- [x] these layers have max zoom 18 so that's as deep as the map will go; 20 would be nice but need to find base maps that aren't ugly
  - [x] find a photo/sat that goes to 20 and covers NYC _update: this ESRI one will only go to 19 but that's as good as it gets. not even Bing goes past 19 here_
  - [x] find a plain reference map that goes to 20 and covers NYC _update: Voyager only goes to 19 but has building numbers so great for referencing specific buildings and locations_

**URL param functions**

- [x] the `?id=` param is matched against `cartodb_id` but should be against `id` which is its MySQL id

- [x] URL param `&latlng=` to center a lat-lng without using a specific obstruction point (already saw that coming, factored code accordingly)

**calling out the selected point**

- [x] when a `id` is used and a specific obstruction is focused, its infowindow opens. _Carto infowindfows are not Leaflet popups and are in a different pane, always come on top, ..._ discuss whether we want these infowindows for obstruction points, may need to refactor as SQL queries and proper L.Popup

- [x] when a `id` is used and a specific obstruction is focused, seems that the point should be visually distinct e.g. double the size
  - [x] not readily supported by CartoCSS and I shelved it at the time
  - [x] if we do go for a larger icon, could obscure neighboring icons; can CartoCSS define z-index ?

**the 311 markers & behaviors**

- [x] icon style for the 311 points; currently a simple but ugly DivIcon

- [x] 311 point behavior, e.g. click popup table? this was a guess on my part, and "seemed" like the most interesting fields from what was available

- [x] these are absent from Carto's auto-generated legend; can I reprogram the CartoCSS to add them, even if it means client-side JS hacking?
  - [x] don't forget to update this legend version when style is finalized

- [x] layer stacking note: 311 markers will always obscure obstruction markers -- Carto layer is a graphical TileLayer in the tiles pane, while 311s are true L.Markers in a vector overlays pane. Only workaround is a total refactor to fetch the obstructions table and create markers, which brings the known issues once we have 15,000 obstructions instead of 100.

**311 query**

- [x] finalize circle radius for 311 queries; 50 is barely one intersection, currently 250 (a city block or so) to give more to see during development

- [ ] per #1 discuss which complaints we really need, e.g. taxi complaints and vendor complaints seem out of place if the idea is disrepair

**Comment by gregallensworth** [comment]
Behavior changes, now that we've started discussing the specification (after programming it, LOL).

- [x] when `&id=` is given, do not open the infowindow for the point. But do keep its size & sorting behaviors.

- [x] the obstruction points to display are _only those within 50 meters of the given id / latlng / lnglat_ and not all obstructions. In fact, given this much smaller set of points (never more than 50ish, let alone 15,000) we could do fetch a SQL GeoJSON and create proper L.Marker instead of using the viz instead... _so a completely 100% different approach to almost every line of code written so far_
  - [x] startup: if latlng or lnglat then use that, else if id then look up that point's latlng and use that (startup will be either synchronous or asynchronous depending on this)
  - [x] with that latlng, do the 311 query as presently done
  - [x] then query for CARTO obstructions within 50 meters with GeoJSON return value
    - [x] SQL query
    - [x] create L.markers
      - [x] replicate/duplicate the 3 types of circle marker: Crossing, Curb, Sidewalk
      - [x] and if the marker's `id` matches the URL's `id` param (if given) it gets an extra-big marker (different approach: marker size, instead of CartoCSS hacking)

- [x] giving up CARTO's auto-generated map also means legend: create a new legend just like the current one

**Comment by gregallensworth** [comment]
- [x] attribution
  - [x] not showing for basemaps
  - [x] and for using CARTO
