### ISSUE TITLE
New request -- download info on map as CSV

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/nyc-walkmaper#3]
This is a bit weird, esp since client wants only a 50 foot! radius, but she's also interested in allowing users to download the items on the map as CSV.

We should be able to do this with the same links we use to load the data, just changing format to `csv` from `json` 

Since the Walkmapper and 311 have different schemas and different endpoints, we'd need two links. Something like this:
![image](https://user-images.githubusercontent.com/1423200/135692213-c9bc2d18-3f12-400e-9b04-71e71ffddffc.png)

I mentioned to her that esp since she had me change radius to 15 meters (!!) there's hardly be anything in those CSVs, it seems weird to offer download, but she ssaid it's useful even if only 1 thing, so you can use the info to write to officials with more complaints about the complaints.

One thing that would be nice would be hiding or at least clear disabling download links when there are no results to download

**Comment by gregallensworth** [comment]
Stuff like this is why we can never go with prefab drag-n-drop maps, and why Open Source rocks. A custom map control that has two specific links, which are dynamically updated to have hyperlinks to SQL queries, and must be managed from the outside since the SQL and the map control are at two different phases... Drag-n-drop Google Maps just don't do that, and React would take a month to do it.  :)

- [x] new map control that contains 2 hyperlinks + download icon
  - [x] and a method to find a link by ID, and update its href

- [x] confirm that BOTH the NYC 311 Socarata endpoint AND the CARTO endpoint accept alternative `&format=` params AND ALSO that they then have the proper behavior when visited, to download the CSV data instead of something goofy
  - [x] NYC 311 Socrata
  - [x] CARTO

- [x] on startup, after executing the SQL statement to get data, update the corresponding hyperlink's `href` in the control

**Comment by danrademacher** [comment]
Both APIs do have CSV endpoints, though they are a bit different.

For Socrata, the root url changes:
`https://data.cityofnewyork.us/resource/erm2-nwe9.json`
to
`https://data.cityofnewyork.us/resource/erm2-nwe9.csv`

And for CARTO, the `format=GeoJSON` changes to `format=CSV`

**Comment by gregallensworth** [comment]
Example URL
* http://localhost:6745/?latlng=40.75591,-73.994497
* https://greeninfo-network.github.io/nyc-walkmapper/?latlng=40.75591,-73.994497

Has 2 threeoneone complaints.

Has 13 walkmapper points, at 3 different coordinates. There is a lot of overlap / multiple reports of the same point, which I guess is exactly what she was looking for!

**Comment by gregallensworth** [comment]
Nice!

![image](https://user-images.githubusercontent.com/3117633/135902046-3fcc180e-de31-4d8f-80fc-836f1db041a3.png)
